apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "static-html.fullname" . }}
  labels:
    {{- include "static-html.labels" . | nindent 4 }}
data:
  website.conf: |-
    {{ .Files.Get "config/envoy.conf" | nindent 4 }}