apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "static-html.fullname" . }}
  labels:
    {{- include "static-html.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "static-html.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "static-html.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "static-html.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: [ "/bin/sh -c sleep 6000" ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: www-data
              mountPath: /usr/share/nginx/html
            - name: config
              mountPath: /etc/nginx/conf.d/website.conf
              subPath: website.conf
        {{- if .Values.gitSync }}
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.3.5
          command: [ "/bin/sh -c sleep 6000" ]
          #args: 
          #  - --ssh
          #  - --repo={{ .Values.gitRepo }}
          #  - --branch={{ .Values.gitBranch }}
          #  - --depth=1
          #  - --wait=360
          #  - --root=/html
          volumeMounts:
            - mountPath: /html
              name: www-data
            - mountPath: /etc/git-secret
              name: ssh-deploy-key
        {{- end }}
      volumes:
        - name: www-data
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "static-html.fullname" . }}
        - name: ssh-deploy-key
          secret:
            secretName: {{ .Values.deploykey }}
            defaultMode: 0400
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
